# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-21 20:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedembeds',
            name='author_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='savedembeds',
            name='author_url',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='savedembeds',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='savedembeds',
            name='height',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='savedembeds',
            name='html',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='savedembeds',
            name='provider_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='savedembeds',
            name='provider_url',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='savedembeds',
            name='thumbnail_height',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='savedembeds',
            name='thumbnail_url',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='savedembeds',
            name='thumbnail_width',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='savedembeds',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='savedembeds',
            name='type',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='savedembeds',
            name='version',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='savedembeds',
            name='width',
            field=models.IntegerField(null=True),
        ),
    ]
